name: Test Sanity Checks 

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

jobs:
  windows:
    name: run on windows
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - uses: microsoft/setup-msbuild@v1
    - name: Build app for release
      run: msbuild src\TestProject.vcxproj -t:rebuild -verbosity:diag -property:Configuration=Release
    - name: Build app for debug
      run: msbuild src\TestProject.vcxproj -t:rebuild -verbosity:diag -property:Configuration=Debug
