name: Test Sanity Checks 

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

jobs:
  windows:
    name: run on windows
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Process cwd
      run: dir
    - name: setup-msbuild
    - uses: microsoft/setup-msbuild@v1
    # - name: Build app for release
      # run: msbuild src\YourProjectFile.csproj -t:rebuild -verbosity:diag -property:Configuration=Release
    # - name: run
      # run: |
        # spark.exe test.spark
      # shell: cmd
    # - name: upload executable
    #   uses: actions/upload-artifact@v2
    #   with:
    #     name: windows
    #     path: |
    #       spark.exe