name: Test Sanity Checks 

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]


permissions:
  contents: read


jobs:
  windows:
    name: run on windows
    runs-on: windows-latest

    strategy:
      matrix:
        configuration: [Release, Debug]

    steps:
    - uses: actions/checkout@v3

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Restore NuGet packages
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: nuget restore ${{env.SOLUTION_FILE_PATH}}

    - name: Build app for ${{ matrix.configuration }}
      run: msbuild src\TestProject.vcxproj -t:rebuild -verbosity:normal -property:Configuration=${{ matrix.configuration }}

    - name: Run app
      run: src\${{ matrix.configuration }}\TestProject.exe
      shell: cmd
